### ISSUE TITLE
libpocketsphinx not found

### ISSUE THREAD

**Issue by psibre** [coli-saar/dialogos#26]
I'm on OSX 10.11 and get this:
```
> Task :run 
2018-01-16 16:03:28.862 java[37257:37093531] ApplePersistence=NO
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3392074444195779/libpocketsphinx_jni.dylib: dlopen(/private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3392074444195779/libpocketsphinx_jni.dylib, 1): Library not loaded: /usr/local/lib/libpocketsphinx.3.dylib
  Referenced from: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3392074444195779/libpocketsphinx_jni.dylib
  Reason: image not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.clt.resources.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:111)
        at de.saar.coli.dialogos.pocketsphinx.PocketSphinx.<clinit>(PocketSphinx.java:52)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin$SphinxHolder.<clinit>(Plugin.java:118)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.getRecognizer(Plugin.java:134)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.initialize(Plugin.java:32)
        at com.clt.dialogos.plugin.PluginLoader.loadPlugins(PluginLoader.java:40)
        at com.clt.dialogos.DialogOS.main(DialogOS.java:129)
```
(I did `brew install cmu-libpocketsphinx` to no avail.)

**Comment by alexanderkoller** [comment]
Hi Ingmar, I just pushed a change. Could you test it?

**Comment by psibre** [comment]
@alexanderkoller Sorry, took me until now to get back to the machine that allows me to test this.

**Comment by psibre** [comment]
I'm still getting an error, albeit a slightly different one:
```
$ ./gradlew run

> Task :plugins:DialogOS_PocketSphinxPlugin:compileJava 
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run 
2018-01-22 12:03:40.145 java[64663:42616967] ApplePersistence=NO
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3896113927595948/libpocketsphinx.3.dylib: dlopen(/private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3896113927595948/libpocketsphinx.3.dylib, 1): Library not loaded: /usr/local/lib/libsphinxbase.3.dylib
  Referenced from: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils3896113927595948/libpocketsphinx.3.dylib
  Reason: image not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.clt.resources.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:111)
        at de.saar.coli.dialogos.pocketsphinx.PocketSphinx.<clinit>(PocketSphinx.java:51)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin$SphinxHolder.<clinit>(Plugin.java:118)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.getRecognizer(Plugin.java:134)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.initialize(Plugin.java:32)
        at com.clt.dialogos.plugin.PluginLoader.loadPlugins(PluginLoader.java:40)
        at com.clt.dialogos.DialogOS.main(DialogOS.java:129)
<============-> 98% EXECUTING [1m 54s]
> :run
```
The GUI just hangs at that stage:
![dialogos](https://user-images.githubusercontent.com/1278639/35217748-a3ef72fe-ff6c-11e7-9f2b-7c250bae1a7a.png)

**Comment by timobaumann** [comment]
same for me on linux.

**Comment by dmhowcroft** [comment]
Me three, on Fedora 27. 

I also tried installing pocketsphinx using my system's package manager, but it still hangs on the same screen Timo reports after a reboot.

**Comment by alexanderkoller** [comment]
Hi all,

I can't reproduce this bug on the machines I have access to, but I just pushed code that might fix the problem, and will produce some debugging output otherwise. Could you pull the latest version and try again? If the problem persists, please copy & paste all messages that are printed to the console and that start with `[#26]`.

Thanks!

Best,
Alexander.

**Comment by alexanderkoller** [comment]
Also, could one of you Linux users please copy & paste the precise exception? Thanks!

**Comment by psibre** [comment]
```
> Task :run 
2018-02-06 08:59:38.347 java[73498:14508760] ApplePersistence=NO
[#26] tempdir: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libsphinxbase.3.dylib
[#26] loaded: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libsphinxbase.3.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libpocketsphinx.3.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libpocketsphinx.3.dylib: dlopen(/private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libpocketsphinx.3.dylib, 1): Library not loaded: /usr/local/lib/libsphinxbase.3.dylib
  Referenced from: /private/var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1117005306602532/libpocketsphinx.3.dylib
  Reason: image not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.clt.resources.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:113)
        at de.saar.coli.dialogos.pocketsphinx.PocketSphinx.<clinit>(PocketSphinx.java:51)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin$SphinxHolder.<clinit>(Plugin.java:118)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.getRecognizer(Plugin.java:134)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.initialize(Plugin.java:32)
        at com.clt.dialogos.plugin.PluginLoader.loadPlugins(PluginLoader.java:41)
        at com.clt.dialogos.DialogOS.main(DialogOS.java:115)
```
Note the line referring to `/usr/local/lib/libsphinxbase.3.dylib` -- there is no such file on my system.
```
$ ll /usr/local/lib/*sphinx*
lrwxr-xr-x  1 ingmar  staff  58 Jan 16 16:03 /usr/local/lib/libpocketsphinx.1.dylib -> ../Cellar/cmu-pocketsphinx/0.8/lib/libpocketsphinx.1.dylib
lrwxr-xr-x  1 ingmar  staff  52 Jan 16 16:03 /usr/local/lib/libpocketsphinx.a -> ../Cellar/cmu-pocketsphinx/0.8/lib/libpocketsphinx.a
lrwxr-xr-x  1 ingmar  staff  56 Jan 16 16:03 /usr/local/lib/libpocketsphinx.dylib -> ../Cellar/cmu-pocketsphinx/0.8/lib/libpocketsphinx.dylib
lrwxr-xr-x  1 ingmar  staff  52 Jan 16 16:03 /usr/local/lib/libsphinxad.0.dylib -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxad.0.dylib
lrwxr-xr-x  1 ingmar  staff  46 Jan 16 16:03 /usr/local/lib/libsphinxad.a -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxad.a
lrwxr-xr-x  1 ingmar  staff  50 Jan 16 16:03 /usr/local/lib/libsphinxad.dylib -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxad.dylib
lrwxr-xr-x  1 ingmar  staff  54 Jan 16 16:03 /usr/local/lib/libsphinxbase.1.dylib -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxbase.1.dylib
lrwxr-xr-x  1 ingmar  staff  48 Jan 16 16:03 /usr/local/lib/libsphinxbase.a -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxbase.a
lrwxr-xr-x  1 ingmar  staff  52 Jan 16 16:03 /usr/local/lib/libsphinxbase.dylib -> ../Cellar/cmu-sphinxbase/0.8/lib/libsphinxbase.dylib
```

**Comment by dmhowcroft** [comment]
After running `./gradlew run` finishes with whatever (re)compilation is necesssary, I get the following:

```
> Task :run
[#26] tempdir: /tmp/nativeutils9235852721142
[#26] lib file: /tmp/nativeutils9235852721142/libpocketsphinx_jni.so
[#26] POSIX compliance: [owner, dos, basic, posix, user, unix]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/nativeutils9235852721142/libpocketsphinx_jni.so: libpocketsphinx.so.3: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.clt.resources.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:113)
        at de.saar.coli.dialogos.pocketsphinx.PocketSphinx.<clinit>(PocketSphinx.java:55)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin$SphinxHolder.<clinit>(Plugin.java:118)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.getRecognizer(Plugin.java:134)
        at de.saar.coli.dialogos.pocketsphinx.plugin.Plugin.initialize(Plugin.java:32)
        at com.clt.dialogos.plugin.PluginLoader.loadPlugins(PluginLoader.java:41)
        at com.clt.dialogos.DialogOS.main(DialogOS.java:115)
```

**Comment by alexanderkoller** [comment]
Hi,

I just pushed changes - both for Linux and for MacOS - that work for me on both MacOS and Linux. Could you test on your side? Thanks!

The problems were:
- On Linux, I loaded the dynamic libraries in the wrong order.
- On MacOS, it turns out that the default Makefiles for Pocketsphinx produce dynamic libraries that have the path to their dependencies hard-coded into them. I now fixed that, so the dynamic library looks for the dependency in the directory in which it is located itself.

Best,
Alexander.

**Comment by dmhowcroft** [comment]
Resolved the issue for me

**Comment by psibre** [comment]
Works for me as well:
```
> Task :run 
2018-02-07 12:33:55.046 java[88486:16879606] ApplePersistence=NO
[#26] tempdir: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libsphinxbase.3.dylib
[#26] loaded: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libsphinxbase.3.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libsphinxad.3.dylib
[#26] loaded: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libsphinxad.3.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libpocketsphinx.3.dylib
[#26] loaded: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libpocketsphinx.3.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
[#26] lib file: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libpocketsphinx_jni.dylib
[#26] loaded: /var/folders/6j/t1lj7h4x0g91bjmxdn5cgv_h0000gn/T/nativeutils1216267615820314/libpocketsphinx_jni.dylib
[#26] POSIX compliance: [owner, basic, posix, unix]
Hello Example Plugin!
```

**Comment by alexanderkoller** [comment]
Fantastic! Thanks for your feedback and your help in hunting down these bugs. I'm closing the issue.
